management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    availability-zones:
        defaultZone: http://localhost:8761/eureka/