FROM openjdk:17.0.2
WORKDIR /app
COPY ./release/application.jar /app/
RUN mkdir -p /target
EXPOSE 8001
ENV spring.datasource.url=jdbc:postgresql://database-mysql:3306/cimed
ENTRYPOINT ["java", "-jar", "application.jar"]